### ISSUE TITLE
Wrong buttons on homepage Iphone 6S - Chrome/Safari

### ISSUE THREAD

**Issue by Icety** [wouterraateland/ikeetmee#16]
![WhatsApp Image 2019-09-09 at 16 09 05](https://user-images.githubusercontent.com/2795818/64538137-5def0000-d31c-11e9-8170-0c0fb05bc449.jpeg)

The text goes to the next line in the buttons 'Verras me' and 'laat leeg'. 
Which should not since the screen on the iPhone 6s is wide enough.
In emulation mode on chrome-desktop all works as it should.

**Comment by wouterraateland** [comment]
Fixed :)
